spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_reloader}
    username: ${SPRING_DATASOURCE_USERNAME:task_reloader}
    password: ${SPRING_DATASOURCE_PASSWORD:change_me_in_production}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
