spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_reloader
    username: task_reloader
    password: change_me_in_production
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
